# --- Basic site meta ---
title: "Mirages International Inc."
description: "Global e-commerce logistics & customs solutions"
url: "https://mi-exp.com"   # change if using a custom domain
logo: "/assets/images/logo.png"

# --- YAT theme hookup ---
remote_theme: "jeffreytse/jekyll-theme-yat"   # :contentReference[oaicite:0]{index=0}
plugins:             # these are all whitelisted on GitHub Pages
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# --- Navigation (will grow in Step 4) ---
nav:
  - name: Home
    link: /
  - name: About
    link: /about/
  - name: Services
    link: /services/
  - name: Contact
    link: /contact/
