# --- Basic site meta ---
title: "Mirages International Inc."
description: "Global e-commerce logistics & customs solutions"

# The address you will actually visit while testing
url: "https://laoshen22.github.io"
baseurl: "/Mirages"            # leading slash, NO trailing slash

logo: "/assets/images/logo.png"

# --- YAT theme hookup ---
remote_theme: "jeffreytse/jekyll-theme-yat"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# --- Navigation ---
nav:
  - name: Home
    link: /
  - name: About
    link: /about/
  - name: Services
    link: /services/
  - name: Contact
    link: /contact/
